//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lojas
    {
        public int Id { get; set; }
        public string RazaoSocial { get; set; }
        public string NomeFantasia { get; set; }
        public string Cnpj { get; set; }
        public string Email { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string Esatado { get; set; }
        public string Telefone { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string Agencia { get; set; }
        public string Conta { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<bool> Ativo { get; set; }
    
        public virtual Categorias Categorias { get; set; }
    }
}
